name: dartcoin
version: 0.0.0
author: Steven Roose <stevenroose@gmail.com>
description: A Bitcoin library for Dart. Pub-test release.
homepage: http://www.dartcoin.org/
dependencies:
  bignum: '>=0.0.4'
  cipher:
    path: /Users/steven/git/cipher
  collection: any
  crypto: any
  json: any
  json_rpc: any
  asn1lib:
    path: /Users/steven/git/asn1lib
dev_dependencies:
  browser: any
  unittest: any
  uuid: any
