name: dartcoin
version: 0.0.0
author: Steven Roose <stevenroose@gmail.com>
description: A Bitcoin library for Dart. Pub-test release.
homepage: http://www.dartcoin.org/
dependencies:
  bignum: '>=0.0.4'
  cipher: '>=0.5.1'
  collection: any
  crypto: any
  json: any
  json_rpc: any
dev_dependencies:
  browser: any
  unittest: any
  uuid: any
